### ISSUE TITLE
テキストブロックを「複数行」にチェックを入れて使った時に起きる不具合の報告

### ISSUE THREAD

**Issue by y-okamoto-1113** [thinreports/thinreports-generator#101]
1. 「複数行」をチェックした状態で、「基本書式」の値に `{value} 御中` と入力して、PDFを出力すると、渡された `value` は表示されるのですが、 `御中` が表示されません。
「複数行」のチェックを外すと `御中` も表示されます。
  （どちらも「溢れたとき」は「拡張」にしています。）

2. 「複数行」をチェックした状態で、「縦位置」を「下揃え」にすると、テキストブロックの範囲（青くなってる部分）に関係なく、そのテキストブロックが存在するページの最下部に表示されてしまいす。

ご確認をお願いいたします。

**Comment by hidakatsuya** [comment]
ありがとうございます。確認しますね。

**Comment by hidakatsuya** [comment]
> 1. 「複数行」をチェックした状態で、「基本書式」の値に `{value} 御中` と入力して、PDFを出力すると、渡された `value` は表示されるのですが、 `御中` が表示されません。
>    「複数行」のチェックを外すと `御中` も表示されます。
>    （どちらも「溢れたとき」は「拡張」にしています。）

こちらについては既に対応は完了しており、次のバージョンで修正します。
https://github.com/thinreports/thinreports-generator/blob/master/CHANGELOG.md#master

> 2\. 「複数行」をチェックした状態で、「縦位置」を「下揃え」にすると、テキストブロックの範囲（青くなってる部分）に関係なく、そのテキストブロックが存在するページの最下部に表示されてしまいす。

こちらも既知の問題ですが、現在対応中となります。

**Comment by hidakatsuya** [comment]
> 1. 「複数行」をチェックした状態で、「基本書式」の値に `{value} 御中` と入力して、PDFを出力すると、

この問題は [v0.11.0](https://github.com/thinreports/thinreports-generator/blob/master/CHANGELOG.md#0110) で解決されました。
