### ISSUE TITLE
生成した PDF ファイルが Acrobat reader で「埋め込みフォントを抽出できない」エラーになる

### ISSUE THREAD

**Issue by bsdmad** [thinreports/thinreports-generator#102]
![image](https://user-images.githubusercontent.com/123257/73628232-01a5c780-4693-11ea-8be5-4b545fa766b6.png)

いつからか不明ですが、生成した PDF ファイルが添付画像のようなエラーが表示されて正常に表示できなくなりました。表示されない文言はいずれも IPA フォントが指定されている箇所です。

ブラウザ他、手元で表示可否を調べた限りでは以下のようになります。

- Windows
  - MS IE ... ×
  - MS Edge ... ×
  - Chrome ... ○
  - Firefox ... ×
  - Acrobat Reader ... ×
  - Just PDF ... ○
- macOS(Catalina)
  - Chrome ... ○
  - Firefox ... ○

使用している環境は以下のとおりです。

- Ruby 2.6.5.p114
- Rails 5.2.4.1
- thinreports 0.10.3
- thinreports-rails 0.4.0

**Comment by bsdmad** [comment]
https://github.com/prawnpdf/ttfunk/issues/72 にたどり着きました。

私の場合、prawn が使用している ttfunk gem のバージョンが 1.6.0 以降でおかしくなることが確認できました。thinreports の問題ではありませんでしたので close します。お騒がせしました。

**Comment by michaelschmitz** [comment]
Thanks @bsdmad for posting the clarification. Your comment helped solved the problem for me by locking down the version of ttfunk to 1.5.1

**Comment by hidakatsuya** [comment]
私の方でも ttfunk `>= 1.6.0, <= 1.6.1` で問題があることを確認しました。 また、その問題は、1.6.2 以降で解決されているので、1.5.0 に戻すか、1.6.2 以降を使うことで解決できます。

prawn の gemspec では `ttfunk` のバージョンを以下のように指定しているので、 1.6 以降がインストールされてしまうんですね。
https://github.com/prawnpdf/prawn/blob/master/prawn.gemspec#L40

他にも困っている方がいる可能性があるので、この issue は pinned しておきます。

**Comment by hidakatsuya** [comment]
タイトルを英文に変更させてもらいます。

**Comment by hidakatsuya** [comment]
I also confirmed that the problem was reproduced with ttfunk 1.6.0 or 1.6.1. This problem can be solved by using ttfunk 1.5 or 1.6.2.
https://github.com/prawnpdf/ttfunk/issues/72
