### ISSUE TITLE
Ruby 3.0 support

### ISSUE THREAD

**Issue by shugo** [thinreports/thinreports-generator#108]
手元のプロジェクトをRuby 3.0 / Rails 6.1に上げようとしているのですが、おそらく `prawn (~> 2.2.0)` の指定のために依存関係が解決できないようです。
`~> 2.2.0` を `>= 2.2.0` に変更するのは何か問題があるでしょうか。

```
Bundler found conflicting requirements for the Ruby version:
  In Gemfile:
    Ruby

    rails (~> 6.1.0) was resolved to 6.1.0, which depends on
      bundler (>= 1.15.0) was resolved to 2.2.3, which depends on
        Ruby (>= 2.3.0)

    thinreports (>= 0.11.0) was resolved to 0.11.0, which depends on
      prawn (~> 2.2.0) was resolved to 2.2.2, which depends on
        Ruby (~> 2.1)

    thinreports (>= 0.11.0) was resolved to 0.11.0, which depends on
      Ruby (>= 2.4.0)
```

**Comment by hidakatsuya** [comment]
単純に prawn 2.3,2.4 の動作確認ができていないというのが理由になります。とりあえず https://github.com/thinreports/thinreports-generator/pull/109 にPR立てたので対応していきます。

**Comment by hidakatsuya** [comment]
2.4 はともかく 2.3 は互換性を壊す変更が入っているので (マイナーバージョンだけど)、多少対応が必要だと思ってます。

**Comment by hidakatsuya** [comment]
また、prawn 2.4 では ttfunk ~> 1.7 に依存するため、https://github.com/prawnpdf/ttfunk/pull/83 が入るまではパフォーマンスの問題がありそうです。prawn 2.2 では ttfunk ~> 1.5 なので ttfunk 1.5 を使えばその問題は回避できる。

**Comment by shugo** [comment]
ご確認とパフォーマンスに関する情報ありがとうございます。
お手数ですが、ご対応よろしくお願いします。

**Comment by hidakatsuya** [comment]
https://github.com/thinreports/thinreports-generator/pull/109 の PR にて、概ね Ruby 3.0 及び prawn 2.4 への対応が完了しています。思ったよりは影響は小さいものでした。

**Comment by hidakatsuya** [comment]
#109 により、自動的に close されましたが、リリースはまだなので reopen しておきます。

**Comment by hidakatsuya** [comment]
https://github.com/thinreports/thinreports/issues/15 で、Ruby 3.0 support を含む v0.12.0 をリリースしました。

issue の作成ありがとうございました。

**Comment by shugo** [comment]
ご対応ありがとうございました！
