### ISSUE TITLE
Ruby 3.0系とthinreportsの0.12.0の組み合わせでThinreports::Report.generateを呼び出した時にエラーが発生する

### ISSUE THREAD

**Issue by sada** [thinreports/thinreports-generator#115]
## 概要

Ruby 3.0系とthinreportsの0.12.0の組み合わせの時に、`Thinreports::Report.generate` メソッドを呼び出すREADME.mdのサンプルコードを実行するとエラーが発生しました。

### 内容

Ruby 3.0.0と3.0.3で試しました。
以下のようにthinreportsを読み込み、README.mdのサンプルコードを実行すると `ArgumentError` 例外が発生しました。

```
require "thinreports"

Thinreports::Report.generate(filename: 'report.pdf', layout: 'report.tlf') do |report|
  report.start_new_page do |page|
    # :
  end
end
```

https://github.com/thinreports/thinreports-generator/blob/15657a3be091e5ccd8d3572cd52d76d43a2ad71e/README.md?plain=1#L111-L115

以下は表示されたエラーです。

```
/home/sada/.anyenv/envs/rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thinreports-0.12.0/lib/thinreports/report/base.rb:33:in `generate': wrong number of arguments (given 1, expected 0) (ArgumentError)
        from /home/sada/.anyenv/envs/rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thinreports-0.12.0/lib/thinreports/report.rb:17:in `generate'
        from a.rb:3:in `<main>'
```

`Thinreports::Report.generate` の引数で可変長引数とブロックを期待していますが、内部で呼び出している 
`Thinreports::Report::Base.generate` がキーワード引数とブロックを期待しています。
そのメソッドの引数の違いで、エラーとなっているようでした。

試しに `*args` を `**args` に変更するとエラーが発生しなくなりました。

https://github.com/thinreports/thinreports-generator/blob/15657a3be091e5ccd8d3572cd52d76d43a2ad71e/lib/thinreports/report.rb#L16-L18

https://github.com/thinreports/thinreports-generator/blob/15657a3be091e5ccd8d3572cd52d76d43a2ad71e/lib/thinreports/report/base.rb#L33

Ruby 3.0の変更でキーワード引数と通常の引数が分離した影響と思います。

> Keyword arguments are now separated from positional arguments. Code that resulted in deprecation warnings in Ruby 2.7 will now result in ArgumentError or different behavior. [feature#14183]

https://docs.ruby-lang.org/ja/latest/doc/news=2f3_0_0.html

ご確認よろしくお願い致します。

**Comment by hidakatsuya** [comment]
ご報告ありがとうございます！確認します。

**Comment by sada** [comment]
手元の変更をPRにしました。
よろしくお願いします。

**Comment by sada** [comment]
PRがマージされたので、こちらのissueを閉じます。
