### ISSUE TITLE
Why on_generate callback has not been implemented?

### ISSUE THREAD

**Issue by upinetree** [thinreports/thinreports-generator#27]
Hi.

`Report::Base#on_generate` seems to be deleted in the following commit.

https://github.com/thinreports/thinreports-generator/commit/ab2746ca57a910177c94bfc158831edc6ebc3e69#diff-940dd4ebc3296201686dd0dd5d08b395L96

Are there any reason for that? (Just curious :wink:)

**Comment by hidakatsuya** [comment]
@upinetree Because I thought that it can be implemented as below without using #on_generate callback.

```ruby
report = Thinreports::Report.new layout: 'foo.tlf'
report.start_new_page do |page|
  page[:price] = 1000
end

# This is the same as #on_generate callback is invoked before generating?
report.pages.each do |page|
  page[:common_title] = 'Title'
end

report.generate filename: 'foo.pdf'
```

**Comment by upinetree** [comment]
Thanks, I understand it!

Is it correct that `@generate_handler` instance variable and some remaining internal methods are deletable?
I think it might be misread that on_generate callback exists.

Anyway, thank you for your response!

**Comment by hidakatsuya** [comment]
It is exactly as you say. Thank you too for pointing that out :smile:
