### ISSUE TITLE
Italic style の Text が Editor で指定した幅に収まらずに途切れる

### ISSUE THREAD

**Issue by maeda-m** [thinreports/thinreports-generator#29]
[Advanced List - Thinreports Examples](https://github.com/thinreports/thinreports-examples/tree/master/list/advanced) のレイアウトファイル(Editor version 0.7.7.2) を使って Generator version 0.8.0 で生成したPDFにて表題の問題を確認しました。
なお、Editor version 0.8.2 で再保存しても同一の結果となりました。

| ファイル名 | Generator | Editor |
| --- | --- | --- |
| advanced_list.pdf | 0.7.7 | 0.7.7.2 |
| result.pdf | 0.8.0 | 0.7.7.2 |

![not-fit-witdth](https://cloud.githubusercontent.com/assets/943541/8321113/dfdf8782-1a5d-11e5-8780-50c4139239f4.png)

**Comment by hidakatsuya** [comment]
@maeda-m ちなみにイタリック体をやめたらどうなるでしょう？

**Comment by maeda-m** [comment]
@hidakatsuya 
Editor 0.7.7.2 でイタリックを外して、Generator 0.8.0 で生成したPDFは途切れました。
しかし、 Editor 0.8.2 でイタリックを外して生成したPDFは途切れませんでした。
ちなみに、幅はEditorの version で少し異なるみたいです。

![no-italic](https://cloud.githubusercontent.com/assets/943541/8321375/01ae872a-1a61-11e5-89eb-1166cfdd96bd.png)

**Comment by hidakatsuya** [comment]
@maeda-m なるほど。深そうですねぇ。ありがとうございます。

**Comment by hidakatsuya** [comment]
@maeda-m 
Could you confirm with the latest versions. Please close this issue if the problem does not reproduce.

**Comment by hidakatsuya** [comment]
I believe this issue has already fixed in the latest version. So i will close the issue.
