### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by hidakatsuya** [thinreports/thinreports-generator#37]
~~Use with Emoji One: http://emojione.com/
Also refer to http://qiita.com/kijtra/items/6ac8e320646fd5601c2b~~

It won't fix. Please use https://github.com/hidakatsuya/prawn-emoji.

**Comment by mzp** [comment]
:+1:

**Comment by hidakatsuya** [comment]
It won't fix. Please use https://github.com/hidakatsuya/prawn-emoji.

```ruby
gem 'thinreports'
gem 'prawn/emoji'
```
