### ISSUE TITLE
Railsで静的画像が埋め込まれたレイアウトのPDFを生成しようとしたとき、Errno::EACCESエラーが発生する

### ISSUE THREAD

**Issue by ishida-kouki** [thinreports/thinreports-generator#39]
# 環境
* Windows8.1 64bit
* Ruby 2.1.6 p336
* Rails 4.2.3
* thinreports-generator 0.8.1

# エラーメッセージ
<pre>
Errno::EACCES in Controller#action

Permission denied @ unlink_internal - C:/Users/username/AppData/Local/Temp/temp-image20151209-xxxx-xxxxxx
</pre>

# 対処
バージョンを 0.8.0 に落としたことでとりあえず問題なく生成されました。
ちなみに埋め込んだ画像はJPEGファイルでした。

```ruby
gem 'thinreports', '0.8.0'
```

<pre>
$ bundle install
</pre>

**Comment by hidakatsuya** [comment]
@ishida-kouki ご報告ありがとうございます。原因は 0.8.1 で入った PNG の透過処理だと思います。
