### ISSUE TITLE
Error when including some (but not all) images

### ISSUE THREAD

**Issue by willjohnson** [thinreports/thinreports-generator#44]
I've created a report with the Thinreports Editor that includes two images. With one of the images (the smaller in both file size and dimensions) the report is created. But with the second image added I get an error such as the following:

```
ArgumentError (/tmp/temp-image20160202-22791-16qkvtk not found):
  app/controllers/reports_controller.rb:20:in `financial_plan'
```

The corresponding code is:

`		send_data report.generate, filename: 'financial_plan.pdf', 
	                           type: 'application/pdf', 
	                           disposition: 'attachment'
`

The first image is a .png. The second image is a .jpg.

However, it does seem to load if I reduce the filesize down to 10KB from 75KB. So I guess perhaps there is a limit on the size of the included images? Or maybe the controller is trying to create the report prior to the temp image being created (due to the size the temp image takes longer to create than the report)?

**Comment by willjohnson** [comment]
I saw this closed issue: https://github.com/thinreports/thinreports-generator/issues/38

Using thinreports 0.8.0 rather than thinreports-rails or thinreports 0.8.1 seems to allow the image to load.

**Comment by hidakatsuya** [comment]
> Using thinreports 0.8.0 rather than thinreports-rails or thinreports 0.8.1 seems to allow the image to load.

I has confirmed the issue. The issue will be fixed in next major version.

Close this issue, thanks.
