### ISSUE TITLE
 different list

### ISSUE THREAD

**Issue by isaahmdantas** [thinreports/thinreports-generator#47]
How do I create different lists in the generator ? because I create a list , and when I create another error from the list stating that there is .

**Comment by willjohnson** [comment]
If I understand your question (it seems to be cut off) you need to add names to the lists.

```
report.list(:list_one).add_row do |row|
	row.values sample_value: sample_value
end

report.list(:list_two).add_row do |row|
	row.values sample_value: sample_value
end
```

**Comment by hidakatsuya** [comment]
@isaahmdantas Please ask a question in [Google Group](https://groups.google.com/forum/?hl=ja#!forum/thinreports) from next time.

**Comment by isaahmdantas** [comment]
Thank you @willjohnson .  

Okay @hidakatsuya .
