### ISSUE TITLE
Unexpected new line after hyphen

### ISSUE THREAD

**Issue by hidakatsuya** [thinreports/thinreports-generator#50]
- Author: @sozuuuuu
- Original issue: thinreports/thinreports-editor/issues/57

---

I looked around the docs and couldn't find the solution.
### Problem

I render the text below.

```
report.page.item(:text).value <<TEXT
行く川のながれは絶えずして、-しかも本の水にあらず。よどみに浮ぶうたかたは、かつ消えかつ結びて久しくとゞまることなし。世の中にある人とすみかと、またかくの如し。玉しきの都の中にむねをならべいらかをあらそへる、たかきいやしき人のすまひは、代々を經て盡きせぬものなれど、これをまことかと尋ぬれば、昔ありし家はまれなり。
TEXT
```

The generated pdf contains unexpected new line after hyphen.

![2016-03-24 12 11 50](https://cloud.githubusercontent.com/assets/5513797/14007394/a6fd0e7e-f1b9-11e5-9100-da81693f58cc.png)
#### Configuration (text block tool)

![2016-03-24 12 13 58](https://cloud.githubusercontent.com/assets/5513797/14007433/014c298c-f1ba-11e5-83c5-d807f4ce7796.png)

**Comment by eitoball** [comment]
I think that prawn see hyphen character as hard hyped (See [this](https://github.com/prawnpdf/prawn/blob/master/manual/text/line_wrapping.rb))

You can see how prawn does hyphenation with the following code:

```ruby
require 'prawn'
Prawn::Document.generate('sample.pdf') do
  font('ipam.ttf') do
    str = '行く川のながれは絶えずして、-しかも本の水にあらず。よどみに浮ぶうたかたは、かつ消えかつ結びて久しくとゞまることなし。世の中にある人とすみかと、またかくの如し。玉しきの都の中にむねをならべいらかをあらそへる、たかきいやしき人のすまひは、代々を經て盡きせぬものなれど、これをまことかと尋ぬれば、昔ありし家はまれなり。'
    text str
  end
end
```

This is the result.

![before](https://cloud.githubusercontent.com/assets/34205/14096474/045d27d2-f5a4-11e5-9bac-62c2b4af1450.png)

(`ipam.ttf` is from thin reports-generator.)

You can disable automatic hyphenation by passing `disable_wrap_by_char: true` option, but you might get `Prawn::Errors::CannotFit`... You could insert `Prawn::Text::ZWSP` after `、` and `。` to give prawn hints where to break lines. For example,

```ruby
require 'prawn'
Prawn::Document.generate('sample.pdf') do
  font('ipam.ttf') do
    str = '行く川のながれは絶えずして、-しかも本の水にあらず。よどみに浮ぶうたかたは、かつ消えかつ結びて久しくとゞまることなし。世の中にある人とすみかと、またかくの如し。玉しきの都の中にむねをならべいらかをあらそへる、たかきいやしき人のすまひは、代々を經て盡きせぬものなれど、これをまことかと尋ぬれば、昔ありし家はまれなり。'
    str = str.gsub(/([、。])/, "\\1#{Prawn::Document::ZWSP}")
    text str, disable_wrap_by_char: true
  end
end
```

This is the result.

![after](https://cloud.githubusercontent.com/assets/34205/14096491/276eb15a-f5a4-11e5-90a5-b2672242c35a.png)

I don't know how you can solve this in thinreports-generator, but I hope this helps.

**Comment by sozuuuuu** [comment]
Thank you for the detailed description.

I understand why. I didn't know that the hyphen character has such special meaning... I solved this problem by replacing hyphens with zenkaku-hyphens. 

(But I'm wondering... It's not rare to use hyphens as divider (e.g. serial number, product number) and often they appear on multi line text. They should have caused same problem. Why not have been reported yet...?)

**Comment by hidakatsuya** [comment]
I will close this issue now. Feel free to reopen if you feel like your issue is not resolved.
