### ISSUE TITLE
韓国語や中国語のテキストがうまくPDF出力できない

### ISSUE THREAD

**Issue by shoheiyokoyama** [thinreports/thinreports-generator#51]
## ブラウザ
以下のブラウザで確認
- Chrome
- Firefox
- IE

## 環境
- Ruby 2.2.2p95
- Rails 4.2.0
- thinreports 0.8.2

## 概要
韓国語や中国語などのテキストを出力すると___のように表示されてしまいます。
中国語では認識できない中国語漢字のみ表示されないようです。(以下参照)
エディタで直接文字を入力して出力してもRails側で動的に文字を入力しても同様の問題が発生します。
Fontは`Helvetica`ですが、Fontを変えても文字化けが発生します。
バグでなければ、対処方法を教えて頂けると幸いです。

### `안녕하세요 세상`の場合(韓国語)
<img width="451" alt="2016-04-13 10 11 53" src="https://cloud.githubusercontent.com/assets/8734755/14480080/632bf5c8-0160-11e6-9309-2890390ad616.png">

### `如有不明白之处或遇到任何困难，请随时发信息给我`の場合(中国語簡体)
<img width="373" alt="2016-04-13 10 19 53" src="https://cloud.githubusercontent.com/assets/8734755/14480176/48e64b36-0161-11e6-84f6-ffd62fab2cc4.png">

### `全面禁菸。`の場合(中国語繁体)
<img width="84" alt="2016-04-13 10 24 48" src="https://cloud.githubusercontent.com/assets/8734755/14480260/fd782b14-0161-11e6-99c0-e2b8637a5c68.png">

なお、Fontを`IPA 明朝`にすると以下のような文字化けが発生します

<img width="713" alt="2016-04-13 10 51 41" src="https://cloud.githubusercontent.com/assets/8734755/14480649/f1baa32a-0165-11e6-81dc-4dba53371305.png">

**Comment by hidakatsuya** [comment]
@shoheiyokoyama ご報告ありがとうございます。これはフォントの問題で thinreports 固有の問題ではありません。回避方法等については、Google Groups に投稿していただいたスレッドで議論したいと思いますので、この issue は close します。
https://groups.google.com/forum/?hl=ja#!topic/thinreports/VaBN43gOuq4
