### ISSUE TITLE
Generator で出力するフォーマットのバージョン指定が出来るようにして欲しい

### ISSUE THREAD

**Issue by bsdmad** [thinreports/thinreports-generator#67]
6/1(?) に 0.9.0 がリリースされましたが、その際に Generator も 0.9.0 のフォーマットで
tlf ファイルを生成（再生成）するようになったため、稼働中の rails アプリでテンプレを
追加しようとした際に 0.8.2 => 0.9.0 に書き換えられてしまいました。
これによりフォーマットエラーで新しいテンプレートが使用できず、現状、作った
テンプレが使えません。現行システムでは未だ 0.8.2 しか対応していないので、非常に
困りました。

Generator が Chrome アプリになった弊害だと思いますが、今回のような
大幅な変更にも対応できるようにファイル保存時に旧バージョンでも
保存できるようにして頂きたく、お願いいたします。

**Comment by maeda-m** [comment]
@bsdmad さん

ご意見ありがとうございます。問題点は次の2があると考えています。
1. `0.9.0` に自動でアップデートされたのが分からないということ
2. 新しいバージョンへとしてファイル保存または開く際に何も警告が無いこと

上記の問題点については thinreports-editor の方で対応を検討しますが、
取り急ぎ、Editor 0.8.2 と 0.9.0 を共存利用できる方法をお伝えします。

次のどちらかのモードで共存させることができます。先ずは簡易な開発モードをお勧めします。

### 開発モード（動作が少し遅いかもしれませんが簡単です）

1. [Developing > How to clone the source of the Editor](https://github.com/thinreports/thinreports-editor/tree/0.8-stable-chrome#how-to-clone-the-source-of-the-editor) の手順を実施します
2. `0.8-stable-chrome` ブランチに切り替えます
3. [Developing > How to launch development version of the Editor](https://github.com/thinreports/thinreports-editor/tree/0.8-stable-chrome#how-to-launch-development-version-of-the-editor) の手順を実施します
4. 開発モードでの起動ができます

### 本番モード（開発環境の整備が必要です）

1. 開発環境として [README > Developing > Requirements](https://github.com/thinreports/thinreports-editor/tree/0.8-stable-chrome#requirements) にあるソフトウェアをインストールします
2. [Developing > How to clone the source of the Editor](https://github.com/thinreports/thinreports-editor/tree/0.8-stable-chrome#how-to-clone-the-source-of-the-editor) の手順を実施します
3. `0.8-stable-chrome` ブランチに切り替えます
4. [Developing > How to build production version of the Editor](https://github.com/thinreports/thinreports-editor/tree/0.8-stable-chrome#how-to-build-production-version-of-the-editor) の手順を実施します
5. [Developing > How to launch development version of the Editor](https://github.com/thinreports/thinreports-editor/tree/0.8-stable-chrome#how-to-launch-development-version-of-the-editor) の手順を参考に `4.` でビルドされた `thinreports-editor/package` を `パッケージ化されていない拡張機能` として読み込みます
5. 本番モードでの起動ができます

**Comment by hidakatsuya** [comment]
@bsdmad 

古いバージョンの Editor をインストール手順を公式ドキュメントに掲載しました。古いバージョンをインストールしたい場合は、こちらを参考になさってください。
http://www.thinreports.org/documentation/ja/getting-started/installation.html

**Comment by bsdmad** [comment]
ご回答、ありがとうございます。対応方法をご提示いただいて助かります。
今、出先なので確認して報告いたします。

**Comment by bsdmad** [comment]
0.8.2 と 0.9.0 を共存することが出来ましたので、取り敢えずそれで対応することにします。
この issue は close しておきます。

ただ、フォーマットが変わる場合はやはり旧形式も扱えるようにしていただくのがベスト
だと思いますので、そちらは今後、ご検討頂ければ幸いです。
