### ISSUE TITLE
New word wrap behaviour?

### ISSUE THREAD

**Issue by willjohnson** [thinreports/thinreports-generator#70]
Upgraded from thinreports 0.8.0 to 0.9.1. Also using version 0.9.0 of the editor.

Previously text would wrap to a new line without breaking the word over two lines. Now, the lines break word no matter whether I use "keep all" or "break word".

**Comment by hidakatsuya** [comment]
@willjohnson There is no changes for word-wrap feature in between 0.8 and 0.9. Could you show me the PDF and `.tlf` file that have the problem?

**Comment by hidakatsuya** [comment]
Any updates? Close this issue. If you have any updates please ask again at [Discussion Group](https://groups.google.com/forum/#!forum/thinreports).
