### ISSUE TITLE
How to generate table of contents with linked indexes to page

### ISSUE THREAD

**Issue by mukuls-brdsys** [thinreports/thinreports-generator#78]
As the title says, Need to generate table of contents (which i plan to do by using list and some coding, but if feature could be included that would be great).
Roadblock is how to link text block to the page in pdf.

**Comment by hidakatsuya** [comment]
> How to generate table of contents 

Currently, it can't be generated.

> Roadblock is how to link text block to the page in pdf.

Exactly. I think that it might be better to use Prawn's outline feature.
https://github.com/prawnpdf/prawn/tree/master/manual/outline

**Comment by hidakatsuya** [comment]
I will close this issue now. Feel free to reopen if you feel like your issue is not resolved.
