### ISSUE TITLE
How can I use thinreports with the latest version of prawn?

### ISSUE THREAD

**Issue by Cesco869** [thinreports/thinreports-generator#82]
I try to use thinreport but this version is not compatible with the latest version of PrawnPDF.
I have the 2.2.1 version, and thinreports work only with old version.

**Comment by hidakatsuya** [comment]
@Cesco869 

The latest stable version of Thinreports requires Prawn 1.3.0. The next major version 0.10.0 will requires Prawn 2.2.x, and the version is currently under development.
