### ISSUE TITLE
[Rails] With `prawn 2.2.0`. Error `uninitialized constant ActionView::CompiledTemplates::ThinReports`

### ISSUE THREAD

**Issue by kntmrkm** [thinreports/thinreports-generator#84]
I'm using `thinreports-generator` with below env.

- Rails 5.0.3
- thinreports-rails 0.3.0
- thinreports 0.10.0

When use with `prawn 1.3.0` is OK.
But,  `prawn` version upgraded as `2.2.0`. then I got below error.

```
ActionView::Template::Error (uninitialized constant ActionView::CompiledTemplates::ThinReports):
```

So, I did downgrade like below. Now, `thinreports` works well.

```
gem 'thinreports-rails'
gem 'prawn', '1.3.0'
```

**Comment by hidakatsuya** [comment]
Thank you for your report.

It is an issue caused by deleting deprecated top module `ThinReports` in version thinreports 0.10.0.  
https://github.com/thinreports/thinreports-generator/blob/master/CHANGELOG.md#0100

So this problem is in `thinreports-rails`.

**Comment by kntmrkm** [comment]
thanks!
