### ISSUE TITLE
can the report definition be saved as a model attribute?

### ISSUE THREAD

**Issue by pakerimus** [thinreports/thinreports-generator#85]
I'm looking for a tool where the end user can eventually edit the report definition... If I save the contents of the tlf file in the database, should I parse it as a JSON?

**Comment by hidakatsuya** [comment]
The tlf file is in JSON format. If you want to edit it you will need to parse.

**Comment by hidakatsuya** [comment]
Please feel free to reopen this, if you have any comments about this.
