### ISSUE TITLE
Table Creation

### ISSUE THREAD

**Issue by Cesco869** [thinreports/thinreports-generator#86]
In the future can we create tables from the editor?

**Comment by hidakatsuya** [comment]
Sorry, currently we have no plan for the feature. Can you solve your request with [the List tool](https://github.com/thinreports/thinreports-examples/tree/master/list) or [Section Report](https://github.com/thinreports/thinreports/issues/7)?

**Comment by hidakatsuya** [comment]
Please feel free to reopen this, if you have any questions about your issue.
