### ISSUE TITLE
特定の条件でpdfが出力されない 

### ISSUE THREAD

**Issue by toney-skm** [thinreports/thinreports-generator#92]
以下のEditorの設定を行って、特定の文字列を入力するとエラーになります。

・Thinreports Editorの設定
幅:143
高さ:10
サイズ：10
フォント: Helvetica
横位置：左揃え
縦位置：中央揃
複数行：チェックをつける
溢れたとき：縮小
書式種別：なし

・エラーが発生した文字列(2種)
aaaaaaaaaaa a-a_a-a_aaaaa完
a aaaaaa-aaaaaaaaaaaaaaaaa終

・エラーメッセージ
Encoding::CompatibilityError in PrintputController#○○ 
incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)

色々と試しまして、以下の条件をすべて満たす場合には発生します。
・条件
1.文字フォント: Helvetica
2.設定しているサイズ(幅,高さ)を超える文字列を入力している
3.文字列の中 (スペース)と –(ハイフン)が順番に入力されている
4.サイズを超えた際の文字に 日本語と日本語以外の文字が含まれている
　→ - と日本語の間に日本語以外の文字が含まれている

現在利用しているのはRuby193、Thinreports0.7.5です。
Thinreportsのバージョンを0.8.0に上げてfallback_font機能を利用してみましたが、解決しませんでした。
私としては古くから使っているプログラムなので、Rubyのバージョンを上げずに以下2点のどちらかができるようにしたいです。

1.これまで通りの設定で出力できること
2.エラーが発生する場合に別の指定したフォントで出力できること

今回分かった文字列の条件以外にも同じような条件で発生しないかどうかも気になっています。
極力置換などで文字列自体を変えずに対応したいのですが、何か方法はないでしょうか。

**Comment by hidakatsuya** [comment]
かなり時間が経っているので難しいかもしれませんが、そのエラーがどこで発生しているのか把握したいので、エラー発生時の backtrace を教えてください。 thinreports に関わる部分のみで大丈夫です。

もし、すでに解決済み、または解決が不要な状況ということでしたら、この issue を close してください。

**Comment by maeda-m** [comment]
I think it is a problem that is solved in PrawnPDF 2.0.0.
https://github.com/prawnpdf/prawn/blob/master/CHANGELOG.md#vastly-improved-handling-of-encodings-for-pdf-built-in-afm-fonts

**Comment by toney-skm** [comment]
エラーはsend_data実行時に発生していました。
現在はフォントを変更して利用していますので、解決の必要性はありません。
ただ原因については気になっていますので、教えていただけると幸いです。

**Comment by toney-skm** [comment]
I also consider the amount of PrawnPDF.
thanks

**Comment by hidakatsuya** [comment]
@toney-skm 

Thinreports 内でPDF生成の足周りとして使っている prawn の仕様、というのが回答になると思います。

> "built in" AFM fonts that are provided by PDF viewers. These fonts only support the very limited set of internationalized characters specified by the Windows-1252 character encoding,

https://github.com/thinreports/thinreports-generator/issues/92#issuecomment-492032611 のリンク先にあるように、Thinreports で使える Helvetica や Georgia、TimesRoman などの欧文フォントは PDF 生成処理の際 prawn で言うところの "built in" AFM fonts となるため、正しく扱える文字が限定的 です。そのためエンコードでエラーが発生したと思われます。

thinreports 0.7.x は prawn 0.12.0 を使っていますが、その当時は

> Earlier versions of Prawn attempted to transcode UTF-8 to Windows-1252 automatically, but some of our low level features either assumed that text was already encoded properly, or returned text in a different encoding than what was provided because of the internal transcoding operations.

とあるように、 prawn 内部でがんばって UTF-8 から Windows-1252 へ変換してくれていました。今回発生したエラーは、この変換部分で生じたものだと思います。

Prawn 2.0 以降は、リンク先の通り、この自動変換が廃止されており、ASCII-8BIT 以外の文字列を扱う場合は TTF フォントを使用することが原則となっています。Thinreprots のビルトインフォントで言えば、IPAFont がそれにあたります。

Thinreports 0.9 (ぐらい) 以降は Prawn 2.0 ベースとなっているため、日本語などの非ASCII文字を使う場合は IPAFont を使うことが推奨されます。ただし、Thinreports のデフォルトフォールバックフォントを IPAFont にしているため、Helvetica で日本語フォントを指定しても動作はするはずです。

**Comment by hidakatsuya** [comment]
問題自体は解決されているということのようですので、この issue は close します。もし、この件に関して何かコメントがあれば気軽に reopen してください。
