### ISSUE TITLE
how to generate data has unicode characters?

### ISSUE THREAD

**Issue by marknguyen85** [thinreports/thinreports-generator#94]
I want to write unicode text to file an generate to pdf but i've got error.

`Your document includes text that's not compatible with the Windows-1252 character set.
If you need full UTF-8 support, use TTF fonts instead of PDF's built-in fonts.
`

PLz help me. thanks for the support.

**Comment by hidakatsuya** [comment]
The error is an error that has occurred in [prawn](https://github.com/prawnpdf/prawn/blob/a8b0ceabd8fc281c62fc3a02dd2b64ee1e3b515c/lib/prawn/font/afm.rb#L113).

The error occurs when you give a text-box that is set to a Latin-font such as Helvetica a character that can not be converted to Windows-1252 encoding.

Try using `IPAGothic` or `IPAMincho` to the text-box instead.

**Comment by marknguyen85** [comment]
My issue have been resolved with embed unicode font.

**Comment by cavoixanha** [comment]
when use vietnamese error đẹp -> 
![image](https://user-images.githubusercontent.com/11247240/125427295-44a915e6-fee1-4cd9-bc50-8397954bc5a3.png)
how to fix it (i already use `IPAGothic` or `IPAGothic` is don't work show image above)
