### ISSUE TITLE
How can I use thinreports for Rails API ?

### ISSUE THREAD

**Issue by TranBaVinhSon** [thinreports/thinreports-generator#96]
I'm currently using thinreports to generate a temporary PDF file, but I'm struggling with how the response API should look.
(I don't want to upload pdf to Amazon S3 and generate link then get pdf link in API)
Any advice would be much appreciated!

**Comment by eitoball** [comment]
Depending on how large generated PDF is, you might want to encode in base64 and send it. There is an example like https://docs.pdfgeneratorapi.com/#templates-output
