### ISSUE TITLE
How to change background color ?

### ISSUE THREAD

**Issue by TranBaVinhSon** [thinreports/thinreports-generator#98]
Does thinreports provide api to change color of background like :
```
page.item(:text).style(:background-color, '#000000')
```
In my case, I want to change background color of a row in list, for example:
```ruby
    datas.each do |data|
      report.list.add_row do |row|
        row.values col1: data[0],
                   col2: data[1],
                   col3: data[2]
        row.style(:background-color, '#000000')
      end
    end
```
How can I do that ?

**Comment by Sotatek-NgocBach** [comment]
I think `row.style(:fill_color, '#000000')` could help

**Comment by TranBaVinhSon** [comment]
@Sotatek-NgocBach thanks for your help. But it didn't work. When I try `row.style(:fill_color, '#000000')` I got this error:
```
"#<NoMethodError: undefined method `style' for #<Thinreports::Core::Shape::List::SectionInterface:0x00007fb0f7f54a88>>"
````
And tried with `row.item(:col1).style(:fill_color, '#ffffff')`, still got new error:
```
#<Thinreports::Errors::UnknownShapeStyleName: The specified style name, 'fill_color', cannot be used. The available styles are :visible, :bold, :italic, :underline, :linethrough, :align, :valign, :color, :font_size.>
```

**Comment by Sotatek-NgocBach** [comment]
@TranBaVinhSon Did you have an element that wrap all child elements in the row? In my case it's `parent_item`
`row.item(:parent_item).style(:fill_color, '#bcbcbc')`

**Comment by Sotatek-NgocBach** [comment]
@TranBaVinhSon What version of Thinreports are you using?

**Comment by TranBaVinhSon** [comment]
@Sotatek-NgocBach yeah, great solution, I can change the background color 👍 

Anyway, I have another question about how I can create the table in thinreports editor? currently, I create a list and have to draw vertical lines like this? 
<img width="1057" alt="Screen Shot 2019-05-17 at 16 14 21" src="https://user-images.githubusercontent.com/12994069/57915597-10add500-78cc-11e9-9c75-39f65c9d8a04.png">

**Comment by TranBaVinhSon** [comment]
@Sotatek-NgocBach I'm not sure about version, I just clone [Thinreport editor](https://github.com/thinreports/thinreports-editor) and launch Editor on development mode by `yarn start`.

**Comment by Sotatek-NgocBach** [comment]
@TranBaVinhSon You can use List and style to make it looks like a table

**Comment by hidakatsuya** [comment]
@TranBaVinhSon 
> how I can create the table in thinreports editor?

Thinreports has no feature for creating Table and currently we have no plan for it.

@Sotatek-NgocBach Thanks for your support!
